var courses = [
	// 1ª linha
	[
		"Agroecologia",
		"Agronomia",
		"Alimentos",
		"Biocombustíveis",
		"Biotecnologia",
		"Biotecnologia e Bioquímica",
		"Ciência e Tecnologia de Alimentos",
		"Ciências Agrárias",
		"Ciências Biológicas",
		"Ciências Naturais e Exatas",
		"Ecologia",
		"Geofísica",
		"Geologia",
		"Gestão Ambiental",
		"Medicina Veterinária",
		"Meteorologia",
		"Oceanografia",
		"Produção de Bebidas",
		"Produção Sucroalcooleira",
		"Rochas Ornamentais",
		"Zootecnia",
		"Biomedicina",
		"Educação Física",
		"Enfermagem",
		"Esporte",
		"Estética e Cosmética",
		"Farmácia",
		"Fisioterapia",
		"Fonoaudiologia",
		"Gerontologia",
		"Gestão Desportiva e de Lazer",
		"Gestão em Saúde",
		"Gestão Hospitalar",
		"Medicina",
		"Musicoterapia",
		"Naturologia",
		"Nutrição",
		"Obstetrícia",
		"Odontologia",
		"Oftálmica",
		"Optometria",
		"Psicologia",
		"Quiropraxia",
		"Radiologia",
		"Saúde Coletiva",
		"Terapia Ocupacional",
	],
	// 2ª linha
	[
		"Agrimensura",
		"Análise e Desenvolvimento de Sistemas",
		"Aquicultura",
		"Astronomia",
		"Automação Industrial",
		"Banco de Dados",
		"Ciência da Computação",
		"Ciência e Tecnologia",
		"Computação",
		"Construção Civil",
		"Construção Naval",
		"Eletrônica Industrial",
		"Eletrotécnica Industrial",
		"Energias Renováveis",
		"Engenharia Acústica",
		"Engenharia Aeronáutica",
		"Engenharia Agrícola",
		"Engenharia Ambiental e Sanitária",
		"Engenharia Biomédica",
		"Engenharia Bioquímica",
		"Engenharia Cartográfica e de Agrimensura",
		"Engenharia Civil",
		"Engenharia da Computação",
		"Engenharia de Alimentos",
		"Engenharia de Biossistemas",
		"Engenharia de Controle e Automação",
		"Engenharia de Energia",
		"Engenharia de Inovação",
		"Engenharia de Materiais",
		"Engenharia de Minas",
		"Engenharia de Pesca",
		"Engenharia de Petróleo",
		"Engenharia de Produção",
		"Engenharia de Segurança no Trabalho",
		"Engenharia de Sistemas",
		"Engenharia de Software",
		"Engenharia de Telecomunicações",
		"Engenharia de Transporte e da Mobilidade",
		"Engenharia Elétrica",
		"Engenharia Eletrônica",
		"Engenharia Física",
		"Engenharia Florestal",
		"Engenharia Hídrica",
		"Engenharia Industrial Madeireira",
		"Engenharia Mecânica",
		"Engenharia Mecatrônica",
		"Engenharia Metalúrgica",
		"Engenharia Naval",
		"Engenharia Nuclear",
		"Engenharia Química",
		"Engenharia Têxtil",
		"Estatística",
		"Fabricação Mecânica",
		"Física",
		"Geoprocessamento",
		"Gestão da Produção Industrial",
		"Gestão da Qualidade",
		"Gestão da Tecnologia da Informação",
		"Informática Biomédica",
		"Irrigação e Drenagem",
		"Manutenção de Aeronaves",
		"Manutenção Industrial (T/L)",
		"Matemática",
		"Materiais",
		"Mecatrônica Industrial",
		"Mineração",
		"Nanotecnologia",
		"Papel e Celulose",
		"Petróleo e Gás",
		"Processos Metalúrgicos",
		"Processos Químicos",
		"Produção Têxtil",
		"Química",
		"Redes de Computadores",
		"Saneamento Ambiental",
		"Segurança da Informação",
		"Segurança no Trabalho",
		"Silvicultura",
		"Sistemas Biomédicos",
		"Sistemas de Informação",
		"Sistemas de Telecomunicações",
		"Sistemas Elétricos",
		"Sistemas Embarcados",
		"Sistemas para Internet",
		"Transporte",
	],
	// 3ª linha
	[
		"Administração",
		"Administração Pública",
		"Agronegócios e Agropecuária",
		"Animação",
		"Arqueologia",
		"Arquitetura e Urbanismo",
		"Arquivologia",
		"Artes",
		"Artes Visuais",
		"Biblioteconomia",
		"Biossistemas",
		"Ciência da Terra",
		"Ciência e Economia",
		"Ciência e Tecnologia",
		"Ciência e Tecnologia das Águas/do Mar",
		"Ciências Aeronáuticas",
		"Ciências Agrárias",
		"Ciências Atuariais",
		"Ciências Contábeis",
		"Ciências da Natureza e suas Tecnologias",
		"Ciências do Consumo",
		"Ciências Econômicas",
		"Ciências Humanas",
		"Ciências Sociais",
		"Cinema e Audiovisual",
		"Comércio Exterior",
		"Comunicação das Artes do Corpo",
		"Comunicação em Mídias Digitais",
		"Comunicação Institucional",
		"Comunicação Organizacional",
		"Conservação e Restauro",
		"Cooperativismo",
		"Cultura, Linguagens e Tecnologias Aplicadas",
		"Dança",
		"Defesa e Gestão Estratégica Internacional",
		"Design",
		"Design de Games",
		"Design de Interiores",
		"Design de Moda",
		"Direito",
		"Educomunicação",
		"Energia e Sustentabilidade",
		"Escrita Criativa",
		"Estudos de Gênero e Diversidade",
		"Estudos de Mídia",
		"Eventos",
		"Filosofia",
		"Fotografia",
		"Gastronomia",
		"Geografia",
		"Gestão Comercial",
		"Gestão da Informação",
		"Gestão de Cooperativas",
		"Gestão de Recursos Humanos",
		"Gestão de Segurança Privada",
		"Gestão de Seguros",
		"Gestão de Turismo",
		"Gestão Financeira",
		"Gestão Pública",
		"História",
		"História da Arte",
		"Hotelaria",
		"Humanidades",
		"Jogos Digitais",
		"Jornalismo",
		"Letras",
		"Libras",
		"Linguagens e Códigos e suas Tecnologias",
		"Linguística",
		"Logística",
		"Luteria",
		"Marketing",
		"Matemática e Computação e suas Tecnologias",
		"Museologia",
		"Música",
		"Negócios Imobiliários",
		"Pedagogia",
		"Pilotagem Profissional de Aeronaves",
		"Processos Gerenciais",
		"Produção Audiovisual",
		"Produção Cênica",
		"Produção Cultural",
		"Produção Editorial",
		"Produção Fonográfica",
		"Produção Multimídia",
		"Produção Publicitária",
		"Psicopedagogia",
		"Publicidade e Propaganda",
		"Rádio, TV e Internet",
		"Relações Internacionais",
		"Relações Públicas",
		"Saúde",
		"Secretariado",
		"Secretariado Executivo",
		"Segurança Pública",
		"Serviço Social",
		"Serviços Judiciários e Notariais",
		"Teatro",
		"Tecnologia da Informação",
		"Teologia",
		"Tradutor e Intérprete",
		"Turismo",
	],
];